FROM ubuntu:bionic

COPY docker/bin/qemu-arm-static /usr/bin/qemu-arm-static

RUN apt-get update && apt-get install -y \
        nginx

ARG WWWUSER
ARG WWWUSERID
RUN useradd -m $WWWUSER -u $WWWUSERID

RUN mkdir /angular /ember && \
    chown -R $WWWUSER /angular /ember

COPY docker/config/nginx.conf /etc/nginx/nginx.conf
COPY docker/config/homesite_nginx.conf /etc/nginx/sites-enabled/homesite_nginx.conf

RUN rm /etc/nginx/sites-enabled/default

CMD exec nginx